import type { APIContext } from 'astro';
import { getCollection } from 'astro:content';
import { COURSES } from '../config/courses';
import { comparePostsByDateDesc } from '../utils/post-date';
import { getEntryHref } from '../utils/post-path';

const FALLBACK_SITE = 'https://otaviomiranda.com.br';
const RECENT_POST_LIMIT = 30;

type LinkEntry = {
  title: string;
  href: string;
  note?: string;
};

export async function GET(context: APIContext) {
  const site = context.site ?? new URL(FALLBACK_SITE);
  const posts = await getCollection('posts');
  const recentPosts = posts
    .sort(comparePostsByDateDesc)
    .slice(0, RECENT_POST_LIMIT);

  const primaryPages: LinkEntry[] = [
    {
      title: 'Home',
      href: '/',
      note: 'Main page with profile, courses, coupon, recent posts, testimonials, and newsletter sections.',
    },
    {
      title: 'Courses',
      href: '/#courses',
      note: 'Programming courses by Otávio Miranda, including Python, JavaScript, TypeScript, React, Django, NestJS, and GraphQL.',
    },
    {
      title: 'Blog archive',
      href: '/blog/1/',
      note: 'Paginated archive for tutorials, technical notes, AI/security commentary, Linux, DevOps, and software development posts.',
    },
    {
      title: 'Contacts',
      href: '/contacts/',
      note: 'Official contact page with social links, newsletter, GitHub, discussions, RSS, and email.',
    },
  ];

  const discoveryFiles: LinkEntry[] = [
    {
      title: 'RSS feed',
      href: '/rss.xml',
      note: 'Full blog feed generated from the posts collection.',
    },
    {
      title: 'Sitemap index',
      href: '/sitemap-index.xml',
      note: 'Search-engine sitemap generated by Astro during the build.',
    },
    {
      title: 'Robots policy',
      href: '/robots.txt',
      note: 'Crawler policy and sitemap reference.',
    },
  ];

  const postLinks: LinkEntry[] = recentPosts.map(post => ({
    title: post.data.title,
    href: getEntryHref(post),
    note: `${formatDate(post.data.date)}. ${post.data.description}`,
  }));

  const optionalLinks: LinkEntry[] = [
    {
      title: 'YouTube channel',
      href: 'https://www.youtube.com/@otaviomiranda/videos',
      note: 'Programming and technology videos in Brazilian Portuguese.',
    },
    {
      title: 'Newsletter',
      href: 'https://luizomf.substack.com/',
      note: 'Long-form updates and notes outside the main site.',
    },
    {
      title: 'GitHub profile',
      href: 'https://github.com/luizomf',
      note: 'Public code and repositories by Otávio Miranda.',
    },
    {
      title: 'GitHub Discussions',
      href: 'https://github.com/luizomf/otaviomiranda.com.br/discussions',
      note: 'Public forum and giscus-backed blog comment area.',
    },
    ...COURSES.map(course => ({
      title: `Course: ${course.title}`,
      href: course.href,
      note: course.description,
    })),
  ];

  const body = [
    '# Otávio Miranda',
    '',
    '> Personal site and blog by Otávio Miranda, a Brazilian software developer and technology educator. The primary language is Brazilian Portuguese.',
    '',
    'This file is a concise guide for LLMs and agents. It is generated during the Astro static build from site metadata, course data, and the posts content collection. Use the sitemap for exhaustive crawling and the RSS feed for the full blog feed.',
    '',
    'Content themes include Python, JavaScript, TypeScript, web development, Linux, DevOps, AI tooling, security notes, and software engineering education.',
    '',
    formatSection('Primary Pages', primaryPages, site),
    '',
    formatSection('Discovery Files', discoveryFiles, site),
    '',
    `## Recent Posts`,
    '',
    `The list below includes the ${RECENT_POST_LIMIT} most recent posts. For every public URL, use the sitemap index.`,
    '',
    formatLinks(postLinks, site),
    '',
    formatSection('Optional', optionalLinks, site),
    '',
  ].join('\n');

  return new Response(body, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
    },
  });
}

function formatSection(title: string, links: LinkEntry[], site: URL): string {
  return [`## ${title}`, '', formatLinks(links, site)].join('\n');
}

function formatLinks(links: LinkEntry[], site: URL): string {
  return links.map(link => formatLink(link, site)).join('\n');
}

function formatLink({ title, href, note }: LinkEntry, site: URL): string {
  const suffix = note ? `: ${compactWhitespace(note)}` : '';
  return `- [${escapeLinkText(title)}](${resolveHref(href, site)})${suffix}`;
}

function resolveHref(href: string, site: URL): string {
  if (href.startsWith('http://') || href.startsWith('https://')) return href;
  return new URL(href, site).toString();
}

function escapeLinkText(value: string): string {
  return compactWhitespace(value).replace(/\\/g, '\\\\').replace(/\]/g, '\\]');
}

function compactWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}
